volumes:
  db-store:

services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www
    networks:
      - custom-net

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./infra/nginx:/etc/nginx/conf.d/
    networks:
      - custom-net

  db:
    image: mariadb
    restart: always
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - custom-net

networks:
  custom-net:
    driver: bridge
